### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by Darjusch**
Frontend for the Fitup smartcontract:
* You can connect with your Metamask
* You can create a Bet
* You can get a Bet
* You can payout a Bet
To test:
1. Clone repo.
2. cd into root folder
3. npm install
4. npm deploy
5. copy Fitup.json from the build folder ( Fitup/build/contracts/Fitup.json ) into ( Fitup/client/src/abi/Fitup.json )
6. cd into client folder
7. npm install
8. npm start
9. click enable ethereum button
10. it asks you to connect to Metamask -> Approve
11. Open the dev console
12. Now you can click on Create Bet, Get Bet, Payout Bet and see the result in the console

Problems that might occur:

Currently we have an import problem and need to add "type":"module" into the package.json when we run npm start and take it out when we run truffle deploy.

### CODE REVIEW

**Review by 5h3rr1ll — APPROVED** [review]
👍

**Comment by 5h3rr1ll** [comment]
Getting this error, when I do step 4 and visit the app in the browser, the steps 5,6,7 and 8 doesn't work for me:

image

image

image

**Comment by Darjusch** [comment]
I forgot to add you need to run ganache and select in metamask the localhost network

**Comment by 5h3rr1ll** [comment]
@Darjusch okay, will try it again. 😊

**Comment by 5h3rr1ll** [comment]
Okay now it worked until step 7, but the notion happened anymore. This is the error I found in the console:

image

**Comment by Darjusch** [comment]
I see. Thenwe need to deploy the smartcontract localy aswell.
Cd into the root folder and: truffle migrate
I think then it should work

**Comment by 5h3rr1ll** [comment]
Okay and now there is a problem due to the fact how we use the import statements. If I understand this error right, it complains about the second like in the package.json which is:

{
  "type": "module",
  ...
}


image

**Comment by Darjusch** [comment]
That thing we need to fix.. its so annoying.

You have to either add if its not there or remove it if its in the package json

**Review by Nameer-Alkhayyat — APPROVED** [review]
Sick

**Pull request merged**
